Repository julb/alertmanager-gchat-integration, pull requests merged in 2021-03, with the labels that each got.

#3 Logger: fix level setting
  alertmanager_gchat_integration/app.py
Labels: type: bug

#2 feat: parse dates in alert payload
  alertmanager_gchat_integration/app.py
  setup.py
Labels: type: enhancement

#4 feat: add possibility to send cards
  README.md
  alertmanager_gchat_integration/app.py
Labels: for: team-attention, type: enhancement
